[languages.en.params]
address = "Madrid, Comunidad de Madrid, Spain"
author = "Javinator9889"
copyright = "Copyright &copy; 2020 a theme by [Kross-Hugo](https://github.com/themefisher/kross-hugo)"
description = "This is meta description"
email = "steve.fruits@email.com"
home = "Home"
logo = ""
phone = "+880 2544 658 256"
[languages.en.params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"